name: Fedora
run-name: ${{ github.actor }} running Build
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - "*"
  schedule:
    # Runs at midnight UTC every day (see https://crontab.guru)
    - cron: '0 0 * * *'
jobs:
  build-rpms:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clone & Update submodules
      run: |
        git submodule update --init
        git pull --recurse-submodules
        git submodule update --remote --recursive
      shell: bash

    - name: Install Dependencies
      run: ./subprojects/LenovoLegionLinux/deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash

    - name: Build rpm darkdetect
      run: ./subprojects/build_rpm_darkdetect.sh
      shell: bash

    - name: Build rpm LenovoLegionLinux
      run: |
        ./subprojects/build_rpm_LLL.sh
      shell: bash

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Copy and Generate files - Fedora
      run: |
        sudo apt-get install createrepo-c
        cd fedora
        gpg --armor --export "${{ secrets.GPG_ID }}" > ./pgp-key.public
        sudo rpm --import pgp-key.public
        echo "%_signature gpg
        %_gpg_name Package Manager" > ~/.rpmmacros
        rpm --addsign ./packages/*.rpm
        cd packages
        rm repodata/* || true
        rm ./LLL.repo || true

        echo "[LLL-pkg-repo]
        name=LLL-pkg-repo
        baseurl=https://mrduartept.github.io/LLL-pkg-repo/fedora/packages
        enabled=1
        gpgcheck=1
        gpgkey=https://mrduartept.github.io/LLL-pkg-repo/fedora/pgp-key.public" > ./LLL.repo

        createrepo_c .
        gpg --batch --detach-sign --armor repodata/repomd.xml

      shell: bash

    - name: Commit changes
      run: |
        git fetch
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Add new rpms"
        git pull --rebase
        git push
      shell: bash
