name: Fedora
run-name: ${{ github.actor }} running Build
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - "*"
  schedule:
    # Runs at midnight UTC every day (see https://crontab.guru)
    - cron: '0 0 * * *'
jobs:
  build-rpms:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
    - name: Install Dependencies in Container
      run: |
        sudo dnf install -y git kernel-headers kernel-devel dmidecode lm_sensors PyQt5 python3-yaml python3-pip python3-argcomplete polkit rpmdevtools rpmlint rpm rpm-sign
        sudo dnf install -y dkms openssl mokutil
      shell: bash

    - name: Clone repo and submodules
      uses: actions/checkout@master
      with:
        path: ./LLL-pkg-repo
        submodules: recursive
        fetch-depth: 0

    - name: Update submodules
      run: |
        cd LLL-pkg-repo
        git submodule update --init
        git pull --recurse-submodules
        git submodule update --remote --recursive
      shell: bash

    - name: Build rpm darkdetect
      run: |
        cd LLL-pkg-repo
        ./subprojects/build_rpm_darkdetect.sh
      shell: bash

    - name: Build rpm LenovoLegionLinux
      run: |
        cd LLL-pkg-repo
        ./subprojects/build_rpm_LLL.sh
      shell: bash

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Copy and Generate files - Fedora
      run: |
        cd LLL-pkg-repo/fedora
        gpg --armor --export "${{ secrets.GPG_ID }}" > ./pgp-key.public
        sudo rpm --import pgp-key.public
        echo "%_signature gpg
        %_gpg_name Package Manager" > ~/.rpmmacros
        rpm --addsign ./packages/*.rpm
        cd packages
        rm repodata/* || true
        createrepo_c .
        gpg --batch --detach-sign --armor repodata/repomd.xml

      shell: bash

    - name: Commit changes
      run: |
        cd LLL-pkg-repo
        git fetch
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Add new rpms"
        git pull --rebase
        git push
      shell: bash
