name: Build
run-name: ${{ github.actor }} running Build
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - "*"
  schedule:
    # Runs at midnight UTC every day (see https://crontab.guru)
    - cron: '0 0 * * *'
jobs:
  build-release-debs-rpms:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clone & Update submodules
      run: |
        git submodule update --init
        git pull --recurse-submodules
        git submodule update --remote --recursive
      shell: bash

    - name: Install Dependencies
      run: ./subprojects/LenovoLegionLinux/deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash

    - name: Build pkgs darkdetect
      run: ./subprojects/darkdetect_deb/build_deb_rpm.sh
      shell: bash

    - name: Build pkgs LenovoLegionLinux
      run: |
        cd subprojects/LenovoLegionLinux/deploy
        sudo apt-get install /tmp/deb_darkdetect/python3-darkdetect_1.0.0-1_amd64.deb
        ./build_deb_rpm.sh
      shell: bash

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Copy and Generate files - Ubuntu
      run: |
        cd ubuntu
        cp /tmp/deb_darkdetect/python3-darkdetect_1.0.0-1_amd64.deb ./
        cp /tmp/pkg/lenovolegionlinux-dkms_1.0.0_amd64.deb  ./    
        cp /tmp/pkg/python3-legion-linux_1.0.0-1_amd64.deb ./
        gpg --armor --export "${{ secrets.GPG_ID }}" > ./KEY.gpg
        dpkg-scanpackages --multiversion . > Packages
        gzip -k -f Packages
        apt-ftparchive release . > Release
        gpg --default-key "${{ secrets.GPG_ID }}" -abs -o - Release > Release.gpg
        gpg --default-key "${{ secrets.GPG_ID }}" --clearsign -o - Release > InRelease
        echo "deb [signed-by=/usr/share/keyrings/lll-ppa.gpg] https://${{ github.repository_owner }}.github.io/LLL-pkg-repo/ubuntu ./" > lll-ppa.list
      shell: bash

    - name: Copy and Generate files - Fedora
      run: |
        sudo apt-get install createrepo-c
        cd fedora
        gpg --armor --export "${{ secrets.GPG_ID }}" > ./pgp-key.public
        cp /tmp/deb_darkdetect/python-darkdetect-1.0.0-1.src.rpm ./packages
        cp /tmp/pkg/lenovolegionlinux-1.0-0.src.rpm  ./packages 
        cp /tmp/pkg/python-lenovolegionlinux-1.0.0-1.src.rpm ./packages

        sudo rpm --import pgp-key.public
        echo "%_signature gpg
        %_gpg_name Package Manager" > ~/.rpmmacros
        rpm --addsign ./packages/*.rpm
        cd packages
        rm repodata/* || true
        createrepo_c .
        gpg --batch --detach-sign --armor repodata/repomd.xml

        echo "[LLL-pkg-repo]
        name=LLL-pkg-repo
        baseurl=https://mrduartept.github.io/LLL-pkg-repo/fedora/packages
        enabled=1
        gpgcheck=1
        gpgkey=https://mrduartept.github.io/LLL-pkg-repo/fedora/pgp-key.public" > ./LLL.repo
      shell: bash

    - name: Commit changes
      run: |
        tag=${GITHUB_REF#refs/tags/}
        git fetch
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Add new deb: $tag"
        git push
      shell: bash
