name: Build rpm
run-name: ${{ github.actor }} running Build
on: workflow_dispatch
#  push:
#    branches:
#      - "*"
#  schedule:
    # Runs at midnight UTC every day (see https://crontab.guru)
#    - cron: '0 0 * * *'
jobs:
  build-release-rpm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clone & Update submodules
      run: |
        git submodule update --init
        git pull --recurse-submodules
        git submodule update --remote --recursive
      shell: bash

    - name: Install Dependencies
      run: ./subprojects/LenovoLegionLinux/deploy/dependencies/install_dependencies_ubuntu.sh
      shell: bash

    - name: Build rpm LenovoLegionLinux
      run: |
        cd subprojects/LenovoLegionLinux/deploy
        ./build_rpm.sh
      shell: bash

    - name: Copy and Generate files
      run: |
        cd fedora
        ls /tmp/rpm
        ls ls /var/lib/dkms/lenovolegionlinux/1.0.0/
        ls /var/lib/dkms/lenovolegionlinux/1.0.0/rpm/
        cp /tmp/rpm/lenovolegionlinux-dkms_1.0.0_amd64.rpm  ./    
      shell: bash

    - name: Commit changes
      run: |
        tag=${GITHUB_REF#refs/tags/}
        git fetch
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Add new rpm: $tag"
        git push
      shell: bash